# TODO: Define Prometheus scrape configurations here

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kvstore'
    static_configs:
      - targets: 
          - 'host.docker.internal:9091' # Node 1 metrics
          - 'host.docker.internal:9092' # Node 2 metrics
          - 'host.docker.internal:9093' # Node 3 metrics